lint:
  actions_ci: false
nf_core_version: 3.1.0
repository_type: pipeline
template:
  author: Jasmin Frangenberg, Anan Ibrahim, Louisa Perelo, Moritz E. Beber, James A. Fellows Yates
  description: Pipeline for screening for functional components of assembled contigs
  force: false
  is_nfcore: true
  name: funcscan
  org: nf-core
  outdir: .
  skip_features:
    - igenomes
    - fastqc
  version: 2.1.0dev
